services:

  # Todo: use docker compose include
  postgres:
    image: postgres:latest
    container_name: pg-server
    restart: always
    hostname: pg-server
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pg-network


  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: always
    hostname: redis
    environment:
      - REDIS_ARGS=--requirepass password
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - redis


  notes-api:
    build: NotesAPI
    container_name: notes-api
    hostname: notes-api
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    ports:
      - "8012:8012"
    networks:
      - pg-network
      - redis


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    hostname: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@note.ai
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "80:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - pg-network


volumes:
  postgres_data:
  pgadmin_data:

networks:
  pg-network:
    driver: bridge
  redis:
    driver: bridge
